### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by SlamJam** [ohbobbyboy/bobby_boy#1]
Привет!
Можешь добавить лицензию на код? Хочется [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0) или [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT), чтобы переиспользовать уже имеющиеся наработки, но не понятно против автор или нет. Более [подробно тут](https://help.github.com/articles/licensing-a-repository/)
Спасибо!

**Comment by ohbobbyboy** [comment]
Добавил. MIT
